-- Seed dependencies from js/config*.js DELIVERABLES[].dependencies (generated by scripts/generate-config-seed.mjs)
-- Replaces all dependencies for config-seed-org with the full set from config files.

DO $$
DECLARE
  v_org_id   UUID;
  v_ws_id    UUID;
  v_from_id  UUID;
  v_to_id    UUID;
  r          RECORD;
BEGIN
  SELECT id INTO v_org_id FROM organizations WHERE slug = 'config-seed-org' LIMIT 1;
  IF v_org_id IS NULL THEN RETURN; END IF;
  DELETE FROM dependencies WHERE org_id = v_org_id;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBX Processing cost optimisation' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBX Processing cost optimisation' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBX Processing cost optimisation' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'MasterMind' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'MasterMind' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Bamboo' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Bamboo' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Service Now' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Tibco EBX' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Tagetik' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'TTM' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'TTM' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pitcher' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'OCE' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Acumen JPN' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Acumen JPN' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Tekdan' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Selective Data Replication [OS204]' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M3', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Xtel Kantar' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - MasterMind Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - MasterMind Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'MasterMind' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Sievo' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Coupa' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Service Now' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Basware' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Reporting Factory (RPF)' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'CIO' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Service Now' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Customer Forecast' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Customer Forecast' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Customer Forecast' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'E2E - CFR' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'E2E - CFR' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'E2E - CFR' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AMC Themis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AMC Themis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'QFS E2E' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN SN' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN MCE' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN SF' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'OCE IWS' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'OCE SPO' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN Water Sales' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI tooling installation' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'MSA sign-off' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'START', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Discovery Plan' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Staff Discovery Roles' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'START', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Discovery Plan' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'MSA sign-off' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Discovery — Data & SiL' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Discovery Plan' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'START', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Transition alignment' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Discovery — Data & SiL' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'START', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'KT sessions (Data & SiL)' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Staff Key Roles' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'START', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-dsmf' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Steady state (Data & SiL)' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Staff Steady State' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M1', 'START', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBX Processing cost optimisation' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBX Processing cost optimisation' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBX Processing cost optimisation' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'TTM' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Acumen JPN' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Xtel Kantar' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Pull: Partial Snapshot Ingestion' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - MasterMind Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - MasterMind Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'MasterMind' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Sievo' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Coupa' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Service Now' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'DBS - Magnitude Reports' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Basware' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Reporting Factory (RPF)' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Magnitude' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'CIO' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Service Now' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M1', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Customer Forecast' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Customer Forecast' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Customer Forecast' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'E2E - CFR' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'E2E - CFR' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B4-B6' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'E2E - CFR' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B7-B10' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AMC Themis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'SAP Themis B1-B3' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M2', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AMC Themis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'QFS E2E' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN SN' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN MCE' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN SF' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'OCE IWS' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'OCE SPO' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-onehouse-full' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'IDN Water Sales' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-regional data sharing V3 (RLS/CLS)' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'M3', 'M2', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Remove window.* Globals' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'packages/web Scaffold' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Roadmap Builder — Lite' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'packages/web Scaffold' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Iterative AI Refinement' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Roadmap Builder — Lite' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Workspace CRUD' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Real RBAC Enforcement' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Workspace CRUD' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Org Resolution' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Workspace CRUD' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'BETA', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Dependencies API' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'BETA', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Live Gantt from API' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'React 19 Migration' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Live Gantt from API' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Full RBAC Enforcement' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Real RBAC Enforcement' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Member Invitation Flow' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Workspace CRUD' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Audit Log UI' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Live Gantt from API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Roadmap Builder — SaaS' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Roadmap Builder — Lite' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Roadmap Builder — SaaS' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Risk Register' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Budget Tracking' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Workspace CRUD' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Portfolio View' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Live Gantt from API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Schedule Variance Engine' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Critical Path Analysis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Dependencies API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Real-Time Collaboration' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Weekly KPI Snapshots' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'KPI Dashboards' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Risk Scoring Engine' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Risk Register' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Risk Scoring Engine' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Schedule Variance Engine' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Deadline Forecasting' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Schedule Variance Engine' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'PMO Chat Interface' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Projects & Milestones API' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Status Report Generator' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'PMO Chat Interface' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'BETA', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Anomaly Detection Alerts' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Weekly KPI Snapshots' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI-Assisted Risk Entry' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Risk Register' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Conversational Updates' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'PMO Chat Interface' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'What-If Scenario Analysis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Critical Path Analysis' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'What-If Scenario Analysis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'PMO Chat Interface' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Slack & Teams Bot' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'PMO Chat Interface' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'AI Onboarding Briefing' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Status Report Generator' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, 'LIVE', 'KO', v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Historical Pattern Mining' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Anomaly Detection Alerts' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Cross-Portfolio Analysis' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Portfolio View' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Scenario Planning' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'What-If Scenario Analysis' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'OKR Tracking' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'KPI Dashboards' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

  SELECT id INTO v_ws_id FROM workspaces WHERE org_id = v_org_id AND slug = 'config-roadmapsnap' LIMIT 1;
  IF v_ws_id IS NOT NULL THEN
    SELECT id INTO v_to_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Proactive AI Copilot' LIMIT 1;
    SELECT id INTO v_from_id FROM projects WHERE workspace_id = v_ws_id AND name = 'Historical Pattern Mining' LIMIT 1;
    IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL AND v_from_id <> v_to_id THEN
      INSERT INTO dependencies (from_project_id, to_project_id, from_milestone_key, to_milestone_key, org_id)
      VALUES (v_from_id, v_to_id, NULL, NULL, v_org_id);
    END IF;
  END IF;

END $$;
