-- Backfill group_order into seed workspaces settings (from CONFIG.GROUP_ORDER).
-- Generated by scripts/generate-config-seed.mjs

DO $$
DECLARE
  v_org_id UUID;
BEGIN
  SELECT id INTO v_org_id FROM organizations WHERE slug = 'config-seed-org' LIMIT 1;
  IF v_org_id IS NULL THEN RETURN; END IF;

  UPDATE workspaces SET settings = settings || '{"group_order":["OneSource 2.0","CDS Transversal","CDS Commercial","CDS SF","CDS D2D","Finance PLE Upgrade","SPC/SPO PLE Upgrade","AMEA-CNAO Upgrade"]}'::jsonb
  WHERE org_id = v_org_id AND slug = 'config';

  UPDATE workspaces SET settings = settings || '{"group_order":[]}'::jsonb
  WHERE org_id = v_org_id AND slug = 'config-base';

  UPDATE workspaces SET settings = settings || '{"group_order":["Preliminary actions","MSA and contracting","Staffing and recruiting","AI Setup","Platform Discovery","Service Transition"]}'::jsonb
  WHERE org_id = v_org_id AND slug = 'config-dsmf';

  UPDATE workspaces SET settings = settings || '{"group_order":["OneSource 2.0","CDS Transversal","CDS Commercial","CDS SF","CDS D2D","Finance PLE Upgrade","SPC/SPO PLE Upgrade","AMEA-CNAO Upgrade"]}'::jsonb
  WHERE org_id = v_org_id AND slug = 'config-onehouse-full';

  UPDATE workspaces SET settings = settings || '{"group_order":["Wave 1 – FED","Wave 2 – Controlling Cloud","Wave 3 – Connect, Plex & Others"]}'::jsonb
  WHERE org_id = v_org_id AND slug = 'config-ple2';

  UPDATE workspaces SET settings = settings || '{"group_order":["Phase 0 — Foundation","Phase 1 — React Migration","Phase 2 — SaaS API","Phase 3 — Program Intelligence","Phase 4 — AI Layer 1","Phase 5 — AI Layer 2","Phase 6 — Predictive Portfolio"]}'::jsonb
  WHERE org_id = v_org_id AND slug = 'config-roadmapsnap';

END $$;
